name: Java CI

on:
  push:
    branches: [master, develop]
    
jobs:
  build:
    runs-on: ubuntu-lates
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn clean package
